version: '3.8'
services:
  bitwarden:
    image: vaultwarden/server
    restart: unless-stopped
    volumes:
      - vaultwarden:/data
    environment:
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'true'
      WEBSOCKET_ENABLED: 'true'
    labels:
      # generic
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # vaultwarden http
      - "traefik.http.routers.vaultwarden.entrypoints=web"
      - "traefik.http.routers.vaultwarden.rule=Host(`pw.<REPLACEME>`)"
      - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      # vaultwarden https
      - "traefik.http.routers.vaultwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`pw.<REPLACEME>`)"
      - "traefik.http.routers.vaultwarden-secure.tls=true"
      - "traefik.http.routers.vaultwarden-secure.tls.certresolver=http"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      # vaultwarden websocket http
      - "traefik.http.routers.vaultwarden-websocket-http.entrypoints=web"
      - "traefik.http.routers.vaultwarden-websocket-http.rule=Host(`pw.<REPLACEME>u`) && Path(`/notifications/hub`)"
      - "traefik.http.middlewares.vaultwarden-websocket-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden-websocket-http.middlewares=vaultwarden-websocket-https-redirect"
      - "traefik.http.routers.vaultwarden-websocket-http.service=vaultwarden-websocket"
      # vaultwarden websocket https
      - "traefik.http.routers.vaultwarden-websocket-https.rule=Host(`pw.<REPLACEME>`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket-https.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-websocket-https.tls=true"
      - "traefik.http.routers.vaultwarden-websocket-https.service=vaultwarden-websocket"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012"
    networks:
      traefik:

volumes:
  vaultwarden:
    external: true
    name: vaultwarden

networks:
  traefik:
    external: true